In [3]:
import numpy as np 
import pandas as pd 
import os
import matplotlib.pyplot as plt
import cv2 
print( cv2.__version__)

from keras.utils import to_categorical
from keras.layers import Dense,Conv2D,Flatten,MaxPool2D,Dropout
from keras.models import Sequential

from sklearn.model_selection import train_test_split

np.random.seed(1)


3.4.1


In [4]:
train_images = []       
train_labels = []
shape = (256,256)  
train_path = 'Heroes/'

for filename in os.listdir(train_path):
    if filename.split('.')[1] == 'jpg':
        img = cv2.imread(train_path + filename)
        window_name = 'image'
#         cv2.imshow(window_name, img)
#         cv2.waitKey(0)  
#         cv2.destroyAllWindows()
        # Spliting file names and storing the labels for image in list
        train_labels.append(filename.split('_')[0])
        print("hello: " ,train_labels)
        
        # Resize all images to a specific shape
        
        img = cv2.resize(img, shape)
        
        train_images.append(img)

# Converting labels into One Hot encoded sparse matrix
train_labels = pd.get_dummies(train_labels).values

# Converting train_images to array
train_images = np.array(train_images)

# Splitting Training data into train and validation dataset
x_train,x_val,y_train,y_val = train_test_split(train_images,train_labels,random_state=1)

hello:  ['Logan']
hello:  ['Logan', 'Logan']
hello:  ['Logan', 'Logan', 'Logan']
hello:  ['Logan', 'Logan', 'Logan', 'Logan']
hello:  ['Logan', 'Logan', 'Logan', 'Logan', 'Logan']
hello:  ['Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan']
hello:  ['Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan']
hello:  ['Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan']
hello:  ['Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan']
hello:  ['Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Magneto']
hello:  ['Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Magneto', 'Magneto']
hello:  ['Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Magneto', 'Magneto', 'Magneto']
hello:  ['Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Logan', 'Magneto', 'Magneto', 'Magneto', 'Magneto']
hello:  ['Logan', 'Logan', 'Logan', 'Logan',

In [53]:
# train_labels

In [5]:

test_images = []
test_labels = []
shape = (256,256)
test_path = 'test/'

for filename in os.listdir(test_path):
    if filename.split('.')[1] == 'jpg':
        img = cv2.imread(os.path.join(test_path,filename))
        
        # Spliting file names and storing the labels for image in list
        test_labels.append(filename.split('_')[0])
        
        # Resize all images to a specific shape
        img = cv2.resize(img,shape)
        
        test_images.append(img)
        
# Converting test_images to array
test_images = np.array(test_images)

In [6]:

len(test_labels)

10

In [112]:
# Creating a Sequential model
model= Sequential()
model.add(Conv2D(kernel_size=(5,5), filters=32, activation='tanh', input_shape=(256,256,3,)))
model.add(Conv2D(filters=30,kernel_size = (3,3),activation='tanh'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(filters=30,kernel_size = (3,3),activation='tanh'))
model.add(MaxPool2D(2,2))
model.add(Conv2D(filters=30,kernel_size = (3,3),activation='tanh'))

model.add(Flatten())

model.add(Dense(20,activation='relu'))
model.add(Dense(15,activation='relu'))
model.add(Dense(5,activation = 'softmax'))
    
model.compile(
              loss='categorical_crossentropy', 
              metrics=['acc'],
              optimizer='adam'
             )

In [113]:
model.summary()

Model: "sequential_9"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_36 (Conv2D)           (None, 252, 252, 32)      2432      
_________________________________________________________________
conv2d_37 (Conv2D)           (None, 250, 250, 30)      8670      
_________________________________________________________________
max_pooling2d_20 (MaxPooling (None, 125, 125, 30)      0         
_________________________________________________________________
conv2d_38 (Conv2D)           (None, 123, 123, 30)      8130      
_________________________________________________________________
max_pooling2d_21 (MaxPooling (None, 61, 61, 30)        0         
_________________________________________________________________
conv2d_39 (Conv2D)           (None, 59, 59, 30)        8130      
_________________________________________________________________
flatten_9 (Flatten)          (None, 104430)           

In [116]:
history = model.fit(x_train,y_train,epochs=100,batch_size=5,validation_data=(x_val,y_val))


Train on 36 samples, validate on 13 samples
Epoch 1/100
36/36 [==============================] - 9s 250ms/step - loss: 1.5671 - acc: 0.3056 - val_loss: 1.6165 - val_acc: 0.0000e+00
Epoch 2/100
36/36 [==============================] - 9s 256ms/step - loss: 1.6070 - acc: 0.2778 - val_loss: 1.6177 - val_acc: 0.0000e+00
Epoch 3/100
36/36 [==============================] - 9s 252ms/step - loss: 1.6065 - acc: 0.2778 - val_loss: 1.6187 - val_acc: 0.0000e+00
Epoch 4/100
36/36 [==============================] - 9s 251ms/step - loss: 1.6062 - acc: 0.2778 - val_loss: 1.6198 - val_acc: 0.0000e+00
Epoch 5/100
36/36 [==============================] - 9s 256ms/step - loss: 1.6060 - acc: 0.2778 - val_loss: 1.6204 - val_acc: 0.0000e+00
Epoch 6/100
36/36 [==============================] - 9s 248ms/step - loss: 1.6056 - acc: 0.2778 - val_loss: 1.6215 - val_acc: 0.0000e+00
Epoch 7/100
36/36 [==============================] - 9s 262ms/step - loss: 1.6053 - acc: 0.2778 - val_loss: 1.6228 - val_acc: 0.0000e+

36/36 [==============================] - 10s 265ms/step - loss: 1.5922 - acc: 0.2778 - val_loss: 1.6738 - val_acc: 0.0000e+00
Epoch 61/100
36/36 [==============================] - 9s 260ms/step - loss: 1.5920 - acc: 0.2778 - val_loss: 1.6748 - val_acc: 0.0000e+00
Epoch 62/100
36/36 [==============================] - 9s 246ms/step - loss: 1.5919 - acc: 0.2778 - val_loss: 1.6752 - val_acc: 0.0000e+00
Epoch 63/100
36/36 [==============================] - 9s 254ms/step - loss: 1.5918 - acc: 0.2778 - val_loss: 1.6757 - val_acc: 0.0000e+00
Epoch 64/100
36/36 [==============================] - 9s 256ms/step - loss: 1.5918 - acc: 0.2778 - val_loss: 1.6765 - val_acc: 0.0000e+00
Epoch 65/100
36/36 [==============================] - 9s 244ms/step - loss: 1.5916 - acc: 0.2778 - val_loss: 1.6772 - val_acc: 0.0000e+00
Epoch 66/100
36/36 [==============================] - 10s 269ms/step - loss: 1.5915 - acc: 0.2778 - val_loss: 1.6778 - val_acc: 0.0000e+00
Epoch 67/100
36/36 [=========================

In [129]:
# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

ImportError: cannot import name '_png' from 'matplotlib' (C:\Anaconda\Anaconda3\lib\site-packages\matplotlib\__init__.py)

<Figure size 432x288 with 1 Axes>

In [131]:
!pip install matplotlib==3.1.3


  Using cached matplotlib-3.1.3-cp37-cp37m-win_amd64.whl (9.1 MB)


ERROR: Could not install packages due to an OSError: [WinError 32] Процесс не может получить доступ к файлу, так как этот файл занят другим процессом: 'C:\\Anaconda\\Anaconda3\\Lib\\site-packages\\matplotlib\\mpl-data\\fonts\\ttf\\DejaVuSans.ttf'
Consider using the `--user` option or check the permissions.



In [118]:
checkImage = test_images[0:5]
checklabel = test_labels[0:4]

predict = model.predict(np.array(checkImage))

output = { 0:'Logan',1:'Magneto',2:'Mystique',3:'Professor', 4: 'Storm'}

print("Actual :- ",checklabel)
print(predict)
print("Predicted :- ",output[np.argmax(predict)])


Actual :-  ['Logant', 'Logant', 'Logant', 'Logant']
[[0.20378698 0.23802023 0.21257046 0.16512571 0.18049656]
 [0.20378698 0.23802023 0.21257046 0.16512571 0.18049656]
 [0.20378698 0.23802023 0.21257046 0.16512571 0.18049656]
 [0.20378698 0.23802023 0.21257046 0.16512571 0.18049656]]
Predicted :-  Magneto


In [120]:
results = list()
for test_image, test_label in zip(test_images, test_labels):
    predict = model.predict(np.absarray(test_image))
    results.append(predict)
    
    print()

4

NameError: name 'labels' is not defined